apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fmjiejt89-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/fmjiejt89-dotnet-basic-gitops